import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavigationBottom from "./Pages/Navigation/NavigationBottom";
import styles from "./Style.module.scss";

const inter = Inter({ subsets: ["latin"], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.bodySection}>
        <NavigationBottom>{children}</NavigationBottom>
      </body>
    </html>
  );
}
